# frozen_string_literal: true

# #Coinbase Platform API
# This is the OpenAPI 3.0 specification for the Coinbase Platform APIs, used in conjunction with the Coinbase Platform SDKs.
# The version of the OpenAPI document: 0.0.alpha
# Contact: yuga.cohler@coinbase.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.5.0

# Common files
require 'coinbase/client/api_client'
require 'coinbase/client/api_error'
require 'coinbase/client/version'
require 'coinbase/client/configuration'

# Models
Coinbase::Client.autoload :User, 'coinbase/client/models/user'

# APIs
Coinbase::Client.autoload :UsersApi, 'coinbase/client/api/users_api'

module Coinbase
  module Client
    class << self
      # Customize default settings for the SDK using block.
      #   Coinbase::Client.configure do |config|
      #     config.username = "xxx"
      #     config.password = "xxx"
      #   end
      # If no block given, return the default Configuration object.
      def configure
        if block_given?
          yield(Configuration.default)
        else
          Configuration.default
        end
      end
    end
  end
end
