# frozen_string_literal: true

# #Coinbase Platform API
# This is the OpenAPI 3.0 specification for the Coinbase Platform APIs, used in conjunction with the Coinbase Platform SDKs.
# The version of the OpenAPI document: 0.0.alpha
# Contact: yuga.cohler@coinbase.com
# Generated by: https://openapi-generator.tech
# Generator version: 7.5.0

module Coinbase
  module Client
    VERSION = '0.0.alpha'
  end
end
