=begin
#Coinbase Platform API

#This is the OpenAPI 3.0 specification for the Coinbase Platform APIs, used in conjunction with the Coinbase Platform SDKs.

The version of the OpenAPI document: 0.0.1-alpha

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module Coinbase::Client
  class NetworkIdentifier
    BASE_SEPOLIA = "base-sepolia".freeze
    BASE_MAINNET = "base-mainnet".freeze
    ETHEREUM_HOLESKY = "ethereum-holesky".freeze
    ETHEREUM_MAINNET = "ethereum-mainnet".freeze
    POLYGON_MAINNET = "polygon-mainnet".freeze
    SOLANA_DEVNET = "solana-devnet".freeze
    UNKNOWN_DEFAULT_OPEN_API = "unknown_default_open_api".freeze

    def self.all_vars
      @all_vars ||= [BASE_SEPOLIA, BASE_MAINNET, ETHEREUM_HOLESKY, ETHEREUM_MAINNET, POLYGON_MAINNET, SOLANA_DEVNET, UNKNOWN_DEFAULT_OPEN_API].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if NetworkIdentifier.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #NetworkIdentifier"
    end
  end
end
